### PR TITLE
chore: enhance modal header and align title to left

### PR DESCRIPTION
**Pull request by bigint**
chore: enhance modal header and align title to left

In most of the places we see the header title on left

GitHub

image

Twitter

Screenshot 2021-12-10 at 9 20 16 AM

**Before** (close button is in wrong place)

Screenshot 2021-12-10 at 9 18 05 AM

**After**

Screenshot 2021-12-10 at 9 18 16 AM

### CODE REVIEW

**Comment by bigint** [comment]
It also align with card design to show title on left

image

**Comment by bigint** [comment]
As a part of https://github.com/snapshot-labs/snapshot/issues/853

**Comment by samuveth** [comment]
@bonustrack waiting for your review on this one.

**Comment by bonustrack** [comment]
I sill prefer having the title in center, in many of the modals we got the content aligned in center

**Pull request closed without merging**
