### PR TITLE
Continue refactoring using explore endpoint

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
@bonustrack only need to review last commit https://github.com/snapshot-labs/snapshot/commit/a352a56c35c1497018e21091e5fccf40510ccc04 others are already merged with last PR

**Comment by bonustrack** [comment]
Are the spaces with private: true are hidden?

**Comment by samuveth** [comment]
@bonustrack yes when I test it they where hidden

**Review by bonustrack — APPROVED** [review]
LGTM

**Pull request merged**
