### PR TITLE
feat(): fix push notification on spaces page

### LINKED ISSUE #977: Push notification Safari integration

### LINKED ISSUE #1006: Browser push notification not working?
- Some users are not able to receive notifications
- If the user connects the wallet on the homepage and then goes to the space page, its always unsubscribed even if the user was subscribed.

### PR DESCRIPTION
**Pull request by midgerate**
Fixes #1006

### CODE REVIEW

**Comment by midgerate** [comment]
Created a support ticket for beams, I am getting an error that it wants the beams initialisation on user click (which is what I am doing)

**Comment by bonustrack** [comment]
@midgerate I can not activate the notification when I try on Safari, it just stay on the state with no notification. This is the error i got 
image

**Comment by ChaituVR** [comment]
I get the same error when I tested with browserstack.com 
image
This is the version
image

**Comment by midgerate** [comment]
@bonustrack @ChaituVR I am aware of this issue, and the support team asked me to use promises instead of async await. So I will probably get around it later, I think for now, this PR fixes a couple of issues not related to firefox and we should merge it. We will keep the issue open so that I can come back and look at this safari issue again.

**Review by bonustrack — APPROVED** [review]

**Comment by bonustrack** [comment]
(Havent really tested)

**Review by mktcode — APPROVED** [review]
Code looks good but I don't see how it solves #1006.

**Pull request merged**
