### PR TITLE
fix: Space alias 

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by Todmy** [comment]
still capable of reproducing in chrome

https://github.com/snapshot-labs/snapshot/assets/7693369/06529894-f136-4c09-9490-066a149499bc

steps to reproduce:
1. Go to the home page
2. Run "empty cache and hard reload" in the browser
3. Add any route that should be redirected

**Comment by samuveth** [comment]
> still capable of reproducing in chrome
> 
>  Screen.Recording.2023-09-05.at.09.44.58.mov 
> steps to reproduce:
> 
> 1. Go to the home page
> 2. Run "empty cache and hard reload" in the browser
> 3. Add any route that should be redirected

Hm weird in local it's working. Will try something else

**Comment by samuveth** [comment]
@Todmy can you test it again, it should work now

**Review by Todmy — APPROVED** [review]
tACK

**Pull request merged**
