### PR TITLE
fix: space unread indicator show #1220

### PR DESCRIPTION
**Pull request by Qsnh**
Fixes # .

Changes proposed in this pull request:
- fix: space unread indicator

### CODE REVIEW

**Comment by samuveth** [comment]
Looks good!
Can you also fix the timeline?

**Comment by Qsnh** [comment]
> Looks good! Can you also fix the timeline in this PR?

what's the problem timeline ?

**Comment by samuveth** [comment]
> > Looks good! Can you also fix the timeline in this PR?
> 
> what's the problem timeline ?

The same thing, the unread indicator isn't updating

**Comment by Qsnh** [comment]
> > > Looks good! Can you also fix the timeline in this PR?
> > 
> > 
> > what's the problem timeline ?
> 
> The same thing, the unread indicator isn't updating when you click on timeline

ok, let me take a look

**Comment by Qsnh** [comment]
@samuveth timeline bug has fixed.

**Review by samuveth — APPROVED** [review]
Works well

**Pull request merged**
