### PR TITLE
Added Stargazer Wallet Support

### PR DESCRIPTION
**Pull request by juandavidkincaid**
### Changes
+ Added stargazer option from [snapshot-labs/lock](https://github.com/snapshot-labs/lock/commit/d74a7b149ac88c738bc8be0a2a5d3afa76f3fd97).
+ Added IPFS logo link (CID).

### 🚧 Pending Changes
+ Upstream update from snapshot-labs to the latest version of [snapshot-labs/lock](https://github.com/snapshot-labs/lock/commit/d74a7b149ac88c738bc8be0a2a5d3afa76f3fd97). Our PR in [snapshot-labs/lock](https://github.com/snapshot-labs/lock/commit/d74a7b149ac88c738bc8be0a2a5d3afa76f3fd97) was accepted but there is no new package for now so we could not include it in this PR.

### Notes
https://constellationnetwork.io/discover/wallets-utilities/#stargazer-wallet

### DRIs
[juan@constellationnetwork.io](https://github.com/juandavidkincaid) - cc [alex@constellationnetwork.io](https://github.com/alexbrandes)

### Related
https://github.com/snapshot-labs/lock/pull/63

### Images
image

### CODE REVIEW

**Comment by samuveth** [comment]
@juandavidkincaid I released Lock v0.1.98 now so you can add it on this PR.

**Comment by juandavidkincaid** [comment]
Hello @samuveth, just updated @snapshot-labs/lock, I think it was updated as well in target. I'll be around for following steps...

**Review by samuveth — APPROVED** [review]

**Comment by samuveth** [comment]
@juandavidkincaid can you resolve the conflict, then I'll merge it

**Comment by samuveth** [comment]
Something has come up and it could take some more time before we are able to merge this PR. Will keep you updated

**Comment by juandavidkincaid** [comment]
Hi @samuveth, just passing by to see if there are any updates :]?

**Comment by samuveth** [comment]
@juandavidkincaid Hi, I think I made a mistake about the integration on Lock package. You could just add the wallet as an injected connector here https://github.com/snapshot-labs/lock/blob/master/src/utils.ts

Then you can also remove the stargazer.ts

**Comment by samuveth** [comment]
This will also make this PR redundant as when stargaze is detected it will show in the connect modal instead of metamask

**Comment by juandavidkincaid** [comment]
Hello @samuveth, I may think there is a confusion, we added the whole connector as the stargazer wallet does not bind to `window.ethereum` but to `window.stargazer` this to avoid interoperability issues with other wallets as it happends with some that bind to `window.ethereum`.

As a result we added a connection to the new connector on this pull request changes.

**Comment by samuveth** [comment]
@juandavidkincaid yes your right. We will add stargazer as soon as we have a design to expand for additional wallets on our frontend.

**Pull request closed without merging**
