### PR TITLE
fix: Update shutter URL

### PR DESCRIPTION
**Pull request by ChaituVR**
### Summary
Same as https://github.com/snapshot-labs/sx-monorepo/commit/66e98942a0fbebdb2a63e15b884361d2124fd0e0

### CODE REVIEW

**Comment by wa0x6e** [comment]
I think the url end by `/`

**Comment by ChaituVR** [comment]
> I think the url end with `/`

It looks to be working fine https://snapshot-git-update-shutter-url-snapshot.vercel.app/#/shutterdao0x36.eth/proposal/0x4bb5cf27998b7371d1c69f7d2d0e433d601bcb46e2a2cdd38108a743c432fa35 any reason for `/`?

Also it is without `/` on https://github.com/snapshot-labs/sx-monorepo/commit/66e98942a0fbebdb2a63e15b884361d2124fd0e0

**Comment by wa0x6e** [comment]
It's returning a 301 code, which redirect to the url with `/`. Let's use the final url directly

```
curl -I https://blog.shutter.network/shielded-voting
HTTP/2 301
server: openresty
status: 301 Moved Permanently
location: /shielded-voting/
ghost-cache: MISS
cache-control: public, max-age=31536000
ghost-age: 0
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
date: Fri, 02 Aug 2024 07:20:54 GMT
age: 8470
x-served-by: cache-ams21048-AMS, cache-nrt-rjtf7700059-NRT
x-cache: HIT, HIT
x-cache-hits: 1, 1
x-timer: S1722583255.521994,VS0,VE2
vary: Cookie
x-request-id: 253bef3c-f6de-4ca2-a2d9-8068ed20cf3b
ghost-fastly: true
alt-svc: clear
content-length: 0
```

**Comment by ChaituVR** [comment]
Done done

**Review by wa0x6e — APPROVED** [review]
utAck

**Pull request merged**
