### PR TITLE
Add terms modal and refactor

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
[Add modal to accept term before a submit a vote or a proposal if the space have terms](https://trello.com/c/p5rFeoSS/81-add-modal-to-accept-term-before-a-submit-a-vote-or-a-proposal-if-the-space-have-terms)

**Comment by samuveth** [comment]
Required getUrl from PR https://github.com/snapshot-labs/snapshot.js/pull/218

**Comment by bonustrack** [comment]
@samuveth Can you fix conflict here? I'd like to merge this PR

**Comment by samuveth** [comment]
> @samuveth Can you fix conflict here? I'd like to merge this PR

Just finished it :)

**Comment by bonustrack** [comment]
Thanks!

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
