### PR TITLE
Allow only jpg and png images on upload

### LINKED ISSUE #997: Some avatar aren't showing up
For some reason some avatar aren't showing up, while the link works fine https://snapshot.org/#/orangeprotocol.eth https://snapshot.org/#/orangeprotocol.eth/settings maybe something wrong with file format or the Cloudflare worker. File works here: https://ipfs.fleek.co/ipfs/QmeZAvVPKZogrHBFc9SAfUizDbAcvxkSBnqkFixEYpZhjR Maybe Cloudflare worker failed to resolve the image first and cached the response?

### PR DESCRIPTION
**Pull request by ChaituVR**
FIxes #997

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
Looks good

**Review by midgerate — CHANGES_REQUESTED** [review]
1. The upload button should then only allow jpeg, jpg and png
image

2. If I upload a JSON I see an endless spinner and have no idea if the file is uploading, could not upload or etc. 
image

**Comment by ChaituVR** [comment]
@midgerate I can't see any other option on my browser 🤔 it says "Custom files" only
I have added this 
```
accept="image/jpg, image/jpeg, image/png"
```
Any ideas on how we can block other types that are shown on your screenshot?


 - Fixed the loading issue

**Comment by bonustrack** [comment]
@midgerate Works for you?

**Review by midgerate — APPROVED** [review]

**Pull request merged**
