### PR TITLE
Build app targeting modern browsers with auto fallback

### PR DESCRIPTION
**Pull request by samuveth**
Build app targeting modern browsers with auto fallback

https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode

### CODE REVIEW

**Comment by bonustrack** [comment]
@samuveth It seem that it's breaking the report page, see:
https://bafybeiafzzkbzkjxlk57iajf47b5r4uq6f73hzjq765jf5icubck3y6tbq.on.fleek.co/report.html
One the others PRs it works. Does it work locally for you? I wonder what weight we are saving with this change.

**Comment by samuveth** [comment]
> @samuveth It seem that it's breaking the report page, see:
> https://bafybeiafzzkbzkjxlk57iajf47b5r4uq6f73hzjq765jf5icubck3y6tbq.on.fleek.co/report.html
I'm not sure I understand what this is.

> One the others PRs it works. Does it work locally for you? I wonder what weight we are saving with this change.
Yes, locally it builds and seems to run fine. I think the improvement is pretty big as pretty 100% of the users uses a modern browser. And as we are starting to scale up the app, it will become even more evident I think.

**Comment by bonustrack** [comment]
@samuveth See here: https://snapshot.page/report.html I'd like to keep this working.

**Comment by samuveth** [comment]
@bonustrack Oh I see, can't we get the same in the `vue ui`?

**Comment by samuveth** [comment]
I just checked, somehow `vue ui` doesn't show everything with the Snapshot repo.

**Comment by samuveth** [comment]
@bonustrack I can't find `foamtree` anywhere in this repo. How is this setup?

**Comment by bonustrack** [comment]
@samuveth I'm not sure what you are talking about

**Comment by samuveth** [comment]
@bonustrack this https://snapshot.page/report.html

**Comment by bonustrack** [comment]
@samuveth Ok it's here: https://bafybeicax4cbj72r3nezceuwcpusczfg6uoxdkxwn2a4bq3sxtok26yiwq.on.fleek.co/modern-report.html

**Review by bonustrack — APPROVED** [review]
Looks good

**Pull request merged**
