### PR TITLE
Playground feature 

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Review by bonustrack — COMMENTED** [review]
Looks really cool!
Can you do this:
- Separate sidebar in 2 block, Actions (with play button) and Results
- Use sligthly smaller icon for "play" and primary button color (blue)
- Use `<User>` component for show results addresses with jazzicon
- Add button "Playground" in the strategy page in right side to link to the playground page
- Use `_n()` for the results 

image

**Review by bonustrack — APPROVED** [review]
Looks good!

**Comment by ChaituVR** [comment]
Looks great :) I have one thought.. is it possible/good to load values from `example.json` automatically?

**Comment by ChaituVR** [comment]
Also is it good to have a playground link here also? (to open in new tab) :
image

**Comment by ChaituVR** [comment]
And when we have any error is it possible to show it within UI? or at least a message saying "There is an error please check console"

**Comment by samuveth** [comment]
> Looks great :) I have one thought.. is it possible/good to load values from `example.json` automatically?

Yes that would be great, any ideas how we could easily do that in the frontend?

**Review by bonustrack — APPROVED** [review]
Looks really good now

**Pull request merged**
