### PR TITLE
Update input from route within the search component and refactor

### PR DESCRIPTION
**Pull request by samuveth**
A continuation of https://github.com/snapshot-labs/snapshot/pull/355

### CODE REVIEW

**Comment by samuveth** [comment]
[Networks: when click on a network we should see all the spaces for that network](https://trello.com/c/3prCvdPn/71-networks-when-click-on-a-network-we-should-see-all-the-spaces-for-that-network)

**Comment by ChaituVR** [comment]
@samuveth when we click on search dropdown it should not clear existing search query in URL.. somehow that is clearing now

screenav

**Comment by samuveth** [comment]
> @samuveth when we click on search dropdown it should not clear existing search query in URL.. somehow that is clearing now

Good catch! Pushed the fix

**Review by bonustrack — APPROVED** [review]
Perfect!

**Pull request merged**
