### PR TITLE
[SafeSnap] Display transaction hashes

### PR DESCRIPTION
**Pull request by carlosfebres**
### Description
- Display the full transaction hash on top of the transaction batches
- Display each transaction batch hash
- Display the transaction of each batch as a JSON compatible with [Safe Tasks](https://github.com/gnosis/safe-tasks)

### Screenshot
Screen Shot 2021-12-18 at 6 28 12 PM

### CODE REVIEW

**Comment by bonustrack** [comment]
@samuveth

**Comment by samuveth** [comment]
@carlosfebres looks great! I'm unsure what the `Complete Transaction Hash` is and why does it disappear when I add another transaction to the batch?

**Comment by mktcode** [comment]
I'm also a bit confused. I wasn't able to find any of the hashes on etherscan after the transactions were broadcasted and confirmed.

image
https://rinkeby.etherscan.io/tx/0x7cc6d41d72e9f290afed52fa27474a15454a5e5232a9dfc0690129370b368477
https://rinkeby.etherscan.io/tx/0x1889deebab0c37a80fda8a7044952d3f7dfdf153d707a983d24c16ae76991176

Code-wise there seems to be a lot more going on than just displaying stuff. I'm trying to review [these lines](https://github.com/snapshot-labs/snapshot/pull/1333/files?authenticity_token=YnlCyOAZxdrjXJDs5pcJgdko7%2FExfKG5RmUFZ8kC%2Ffh07Dmvch4FH6quHUeq%2Fp1c0XfwWoY3UJgm8RpbRAF2pw%3D%3D&file-filters%5B%5D=.svg&file-filters%5B%5D=.ts#diff-2b9cd609ca8794aced1ef5d5f2df709e1ebece6e9b9f96e0dd842342669d5213R544-R605) now.
@carlosfebres some comments in the code would be helpful.

Side-note: We should use the [`<script setup>` format](https://www.youtube.com/watch?v=9uSNKIXH_AI) everywhere, at least for [newly added components](https://github.com/snapshot-labs/snapshot/pull/1333/files?authenticity_token=YnlCyOAZxdrjXJDs5pcJgdko7%2FExfKG5RmUFZ8kC%2Ffh07Dmvch4FH6quHUeq%2Fp1c0XfwWoY3UJgm8RpbRAF2pw%3D%3D&file-filters%5B%5D=.svg&file-filters%5B%5D=.vue#diff-b7f59e85e0b077f6a8f54d03667d26cc7bcb02f42bc6fdc4c21dcaed7fc53faf).

**Comment by samuveth** [comment]
> Fill the form then it comes back. It's only displayed when all input is valid.

Oh I see.

> Side-note: We should use the [`<script setup>` format](https://v3.vuejs.org/api/sfc-script-setup.html) everywhere, at least for [newly added components](https://github.com/snapshot-labs/snapshot/pull/1333/files?authenticity_token=YnlCyOAZxdrjXJDs5pcJgdko7%2FExfKG5RmUFZ8kC%2Ffh07Dmvch4FH6quHUeq%2Fp1c0XfwWoY3UJgm8RpbRAF2pw%3D%3D&file-filters%5B%5D=.svg&file-filters%5B%5D=.vue#diff-b7f59e85e0b077f6a8f54d03667d26cc7bcb02f42bc6fdc4c21dcaed7fc53faf).

For existing plugins we agreed that it's alright to continue with options API.

**Comment by mktcode** [comment]
Hmmmmmmmmmmmmmm......... ok. :D

**Comment by carlosfebres** [comment]
> Code-wise there seems to be a lot more going on than just displaying stuff. I'm trying to review [these lines](https://github.com/snapshot-labs/snapshot/pull/1333/files?authenticity_token=YnlCyOAZxdrjXJDs5pcJgdko7%2FExfKG5RmUFZ8kC%2Ffh07Dmvch4FH6quHUeq%2Fp1c0XfwWoY3UJgm8RpbRAF2pw%3D%3D&file-filters%5B%5D=.svg&file-filters%5B%5D=.ts#diff-2b9cd609ca8794aced1ef5d5f2df709e1ebece6e9b9f96e0dd842342669d5213R544-R605) now.
> @carlosfebres some comments in the code would be helpful.

Hi @mktcode, we need to store the hashes in the proposal data stored in IPFS, The batches of transactions were stored as a bi-dimensional array, I made a refactor to store batches as object and support old proposals.

**Comment by carlosfebres** [comment]
> @carlosfebres looks great! I'm unsure what the `Complete Transaction Hash` is and why does it disappear when I add another transaction to the batch?

As @mktcode said, the `Complete Transaction Hash` is only displayed if all transactions are valid.
@samuveth sorry if that's not intuitive, how can we improve it?

**Comment by mktcode** [comment]
First thought: Always show "something".

All valid: show hash
Otherwise: show "form partially filled, complete form to see hash"

You know what I mean? You could even put a gigantic red box above everythign saying "hey... this form will behave weird unless you fill all the fields" That's maybe ugly but clear to the user. Not saying it should be like that but you get the idea?

**Comment by mktcode** [comment]
image

It just says: "The hash is the keccak of the concatenation of the individual EIP-712 hashes..."
Maybe the individual hashes should be posted there too.

I was also a bit confused at first (had to delete a long pointless comment the other day :D) of what "Complete Transaction Hash" actually refers to in this scenario. It might just be me and I got it by now, but first I thought this is about the hash of the actual transaction the safe executes. I understand now, it's the hashed information about the transactions to be executed, stored in the zodiac module. Maybe we can find some more clear wording for this. "Verification Hash"... "Execution Data Hash"... idk. If you're all fine with it as it is, just ignore me. :D

**Comment by carlosfebres** [comment]
@mktcode that's all right, showing the hash for each transaction in a batch is not necessary since each batch is executed using a MultiCall contract, and the hash of the MultiCall transaction is the one shown.
Thanks for taking a time to go through the whole flow.

**Comment by carlosfebres** [comment]
@mktcode @bonustrack if it's all fine, can we merge it?

**Review by mktcode — APPROVED** [review]
Can't see any obvious issues with the code. Works for me with my Rinkeby safe. Hashes match. Approved. :)

**Comment by mktcode** [comment]
Well....

https://bafybeiembm4wteag3g2wzeftimy5xl5pdjhwj5pofhlehntwgmt5bt577e.on.fleek.co/#/fabien.eth/proposal/QmV2TVKZmgXHuzT36ockuJ3hwCY31weotgirYTsA18SBDB

I'll leave it as approved because it does not seem to be related to the changes in this pr. Same here:

https://snapshot.org/#/fabien.eth/proposal/QmV2TVKZmgXHuzT36ockuJ3hwCY31weotgirYTsA18SBDB

**Pull request merged**
