### PR TITLE
Add transaction pending indicator on the UI fixed #556

### LINKED ISSUE #556: Add transaction pending indicator on the UI
When someone doing a transaction in the UI we should show a transaction pending indicator. 
Here is how the design should look like:
image
The first step would be to make it work with the delegation flow, you can try to trigger a transaction on this page, (must connect wallet on Rinkeby): https://snapshot.org/#/delegate

### PR DESCRIPTION
**Pull request by NftTopBest**
Fixes #556  .

Changes proposed in this pull request:
- update cmd for boot-up development
- add pending transaction text and logic
- add lang text into i18n for default.json only

Screen Shot 2021-08-16 at 11 02 01 AM

### CODE REVIEW

**Comment by bonustrack** [comment]
@NftTopBest The block with pending transaction should be in TopNav component, this is something we will use on others pages. Also there can be multiple tx pending, it's not necessary just 1. You may need to make a composable to keep track of the number of pending transactions. 

Also for the design:
- There shouldn't be any space between the top menu and the pending transaction toolbar (the space in red line should not exist).
image
- The loading animation should be white
- There should be a space between the loading animation and the text "1 transaction pending", you can use the class `mr-2` for that.

**Comment by NftTopBest** [comment]
now it looks like this, I make a fake `add` button to add the `pendingCount` in different page to take
Screen Shot 2021-08-16 at 22 01 04
Screen Shot 2021-08-16 at 22 01 10
Screen Shot 2021-08-16 at 22 00 57

**Comment by samuveth** [comment]
@NftTopBest Works well for me. A few things that I found:
- when the space navbar is the same color like in "ybaby.eth" it looks confusing
image
- why are you changing the class ordering here?
image
- also here please run `yarn lint` before you push

**Comment by NftTopBest** [comment]
> @NftTopBest Works well for me. A few things that I found:
> 
> * when the space navbar is the same color like in "ybaby.eth" it looks confusing
>   image
> * why are you changing the class ordering here? These types of changing just make your PR more difficult to read.
>   image
> * also here please run `yarn lint` before you push

1. so how to fix this? show a different bg color while the color is blue? 
2. I use the plugin that it will auto-arrange the tailwind css class's order: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
Should I disable it next time I push new code? 
3. I run `yarn lint`, the code do not have any change.

**Comment by samuveth** [comment]
> 1. so how to fix this? show a different bg color while the color is blue?
> 2. I use the plugin that it will auto-arrange the tailwind css class's order: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
>    Should I disable it next time I push new code?
> 3. I run `yarn lint`, the code do not have any change.

1. You can try using border top with this color `--border-color`
2. We are using Vetur with VScode
3. Strange, maybe it's Volar or your VScode settings. Also check your prettier print width, should be 80 by default https://prettier.io/docs/en/options.html#print-width

**Comment by NftTopBest** [comment]
> 1. --border-color

is that only blue style with the border-color? or make it always with border-color?

**Comment by samuveth** [comment]
> > 1. --border-color
> 
> is that only blue style with the border-color? or make it always with border-color?

I think it should be always

**Comment by NftTopBest** [comment]
> > > 1. --border-color
> > 
> > 
> > is that only blue style with the border-color? or make it always with border-color?
> 
> I think it should be always

How about this?

Screen Shot 2021-08-17 at 23 12 26
Screen Shot 2021-08-17 at 23 12 04

**Comment by samuveth** [comment]
> How about this?

Looks good! Please fix the linting also.

**Comment by NftTopBest** [comment]
> > How about this?
> 
> Looks good! Please fix the linting also.

pls check ;)

**Pull request closed without merging**
