### PR TITLE
Fix dateformat locale issue

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by bonustrack** [comment]
Curious what does PR fix?

**Comment by samuveth** [comment]
> Curious what does PR fix?

@bonustrack I get a lot of warning on the proposal page about fallback locale for shot date format. 
image

**Comment by bonustrack** [comment]
Strange i don't get any of these, do you use en-US as default language in your browser?

**Comment by samuveth** [comment]
> Strange i don't get any of these, do you use en-US as default language in your browser?

Yes.

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
