### PR TITLE
feat: use preview icon instead of search in create proposal page

### LINKED ISSUE #1248: Use eye icon instead of lens for preview markdown
image

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1248 

feat: use preview icon instead of search in create proposal page

image

### CODE REVIEW

**Comment by samuveth** [comment]
@bigint  The icon doesn't seem to be centered

**Comment by bigint** [comment]
@samuveth can you please check now 🙇🏻 

Screenshot 2021-12-16 at 5 27 15 PM

**Review by samuveth — APPROVED** [review]
LGTM

**Pull request merged**
