### PR TITLE
fix(walletconnect): attempt to fix connection with safe wallets

### PR DESCRIPTION
**Pull request by Todmy**
### Issues

Fixes #
wc+safe doesn't support multiple chains connection. This PR attempts to fix it.

### Changes 
*_(Briefly describe the changes made in this PR)_*
1. updated lock
2. removed `chains` from connectors config

### How to test
1. Try to connect with walletconnect using different chains
2. Try to connect with walletconnect using Safe

### To-Do
- [ ] if everything works, need to publish new version of lock and update this PR after

### Self-review checklist
- [x] I have performed a full self-review of my changes
- [x] I have tested my changes on a preview deployment
- [x] I have tested my changes on different screen sizes (sm, md)
- [ ] I have tested my changes on a custom domain

### Additional notes or considerations
*_(Include any other relevant information or context that may be helpful for the reviewer)_*

### CODE REVIEW

**Comment by ChaituVR** [comment]
Is there any link to changes on the lock?

**Comment by ChaituVR** [comment]
weird, doesn't work for me on MM mobile 🤔

**Comment by ChaituVR** [comment]
It works nicely on Safe walletconnect on different network, but fails on MM mobile
It throws this error
image

**Comment by Todmy** [comment]
> It works nicely on Safe walletconnect on different network, but fails on MM mobile It throws this error image

let's wait a little. Maybe other wallets should update the version of walletconnect

**Comment by Todmy** [comment]
> Can this be closed @Todmy?

yes, will reopen it later

**Pull request closed without merging**
