### PR TITLE
fix: remove scroll for textareajson and use its full width

### LINKED ISSUE #1599: Remove Textarea scrollbar and reduce width to parent width
image

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1599

Before

Screenshot 2022-02-02 at 8 39 49 PM

After

Screenshot 2022-02-02 at 8 39 24 PM

### CODE REVIEW

**Review by mktcode — APPROVED** [review]
Yep. Better than before. Annoyed me for long enough now. Thanks. :D

In the long term it would of course be nice to have all JSON config stuff we have get converted to proper input fields like with the strategies. But that fruit hangs a bit higher.

**Comment by samuveth** [comment]
Please don't merge this one yet. Making sure with fabien first.

**Review by samuveth — CHANGES_REQUESTED** [review]
Please remove the `w-full` that you added and add `whitespace-nowrap w-full !overflow-x-scroll no-scrollbar` on `TextareaAutoresize` inside `TextAreaJson` like this
image

This will prevent wrap and hide the scroll bar. Scroll left and right will still be possible tho

**Comment by bigint** [comment]
Thanks addressed the comments 🚀

**Comment by mktcode** [comment]
Doesn't work in Firefox. Puts everything in one line.

image

Something about `white-space: nowrap` but not sure why yet.

**Comment by bigint** [comment]
@mktcode updated it works fine for me 👍🏻

**Comment by samuveth** [comment]
Now it's wrapping the strings on Chrome and Firefox. Also Firefox doesn't look right in terms of indents 
image

**Comment by bigint** [comment]
`whitespace-pre` is working

Chrome

Screenshot 2022-02-04 at 11 13 04 AM

Firefox

image

**Review by samuveth — APPROVED** [review]
Looks great! Thanks @bigint

**Pull request merged**
