### PR TITLE
Connect button instead of vote button - If wallet is not connected

### PR DESCRIPTION
**Pull request by ChaituVR**
aaaa

### CODE REVIEW

**Review by samuveth — DISMISSED** [review]
Works well!

**Comment by samuveth** [comment]
Now that I think about it, I will try refactoring this with a composable. I think it's the cleaner solution as we don't need to add any extra thing to the app module.

**Comment by samuveth** [comment]
@ChaituVR sorry for pushing to your branch. What do you think?

**Comment by ChaituVR** [comment]
@samuveth Hey no no np :) This is great

**Comment by bonustrack** [comment]
Can you make the label of the button to always be "Vote"? Also we should not see the button loading when auth is loading.

**Comment by bonustrack** [comment]
Also the button should be disabled if no open was chosen yet

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
