### PR TITLE
feat(proposal): add ability to flag proposals for admins and moderators

### PR DESCRIPTION
**Pull request by Todmy**
### Feature
[Flag proposals](https://www.notion.so/snapshotlabs/Move-flagged-and-verified-property-to-hub-b6b076290ee34162ac34fa107e99c0cf?pvs=4)

### Changes 
1. Add action under "..." on proposal page

### How to test
1. Open proposal
2. Click on "..."
3. Click "Flag proposal"
Screenshot 2023-09-21 at 13 55 11

4. Sign message
5. Refresh the page, and observe that the proposal is marked 
Screenshot 2023-09-21 at 13 56 09

### To-Do
- [ ] marge [PR](https://github.com/snapshot-labs/snapshot.js/pull/903) from `snapshot.js`
- [ ] upgrade `@snapshot-labs/snapshot.js` to a new version
- [ ] merge [PR](https://github.com/snapshot-labs/snapshot-hub/pull/679) from `snapshot-hub`
- [ ] merge [PR](https://github.com/snapshot-labs/snapshot-sequencer/pull/168) from `snapshot-sequencer`

### Self-review checklist
- [x] I have performed a full self-review of my changes
- [x] I have tested my changes on a preview deployment
- [x] I have tested my changes on different screen sizes (sm, md)
- [ ] I have tested my changes on a custom domain

### Additional notes or considerations
*_(Include any other relevant information or context that may be helpful for the reviewer)_*

### CODE REVIEW

**Comment by samuveth** [comment]
The icon doesn't seem fitting, as the name is `flag` but the icon for the item above is a flag. I think there should be a single button, if "admin" it should enable them to flag the proposal and if "user" it should do the the report form.

**Comment by samuveth** [comment]
When I click flag is throws an error. Is this PR still a draft?

**Comment by Todmy** [comment]
> The icon doesn't seem fitting, as the name is `flag` but the icon for the item above is a flag. I think there should be a single button, if "admin" it should enable them to flag the proposal and if "user" it should do the the report form.

It was discussed [here](https://discord.com/channels/955773041898573854/1031838772490424350/1153663291374178334). I agree that the icon can be not the perfect one. Could you propose another icon for this?

**Comment by Todmy** [comment]
> When I click flag is throws an error. Is this PR still a draft?

it's not a draft, but BE PRs are not merged yet. If you want you can use https://github.com/snapshot-labs/snapshot-infra to run the whole infrastructure with appropriate BE git branches. Let me know if you need any help

**Review by ChaituVR — APPROVED** [review]
tAck

**Pull request merged**
