### PR TITLE
Remove voteId and voteCreated from votes query

### PR DESCRIPTION
**Pull request by samuveth**
Fixes https://github.com/snapshot-labs/snapshot/issues/1578

Changes proposed in this pull request:
- Remove voteId and voteCreated from votes query
- Remove redundant code from UiLoading 

Sorry for the not related change ;)

### CODE REVIEW

**Comment by mktcode** [comment]
> Sorry for the not related change ;)

No problem. Separate commits would have been helpful though. ;) :D

**Comment by mktcode** [comment]
Not everything was redundant it seems. I have a black spinner here now:

image

**Comment by samuveth** [comment]
> * Remove redundant code from UiLoading

You mean this "Remove redundant code from UiLoading"? :D

**Comment by samuveth** [comment]
> Not all of it was redundant it seems. I have a black spinner here now:
> 
> image
> 
> `:fill-white="primary"` doesn't make sense though (except for the button component). Should be just `fill-white` (bool flag)
> 
> Other changes look good but now I can't approve this PR.... hehe. :D

Hmm, that weird, I tested that exact loader

**Comment by samuveth** [comment]
Fixed, this time with Tailwind class tho :)

**Review by mktcode — APPROVED** [review]

**Pull request merged**
