### PR TITLE
Strategy form

### PR DESCRIPTION
**Pull request by samuveth**
Continuation of #1246 

Fixes:
- Persist params when fill the generated form
- Replace textarea with JSON with a component TextareaJson (to move parse / stringify logic)

TODO:
- [x] Load component in SObject dynamically 
- [x] Enhance UI and tune form validations

### CODE REVIEW

**Comment by bonustrack** [comment]
Looks good! You may want to replace all field using JSON content with TextareaJson too

**Comment by samuveth** [comment]
@bonustrack what are these used for?
```
 "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Strategy",
```

Also I'm thinking we should probably have some sort of way we validate the user input inside the SObject form?

**Comment by bonustrack** [comment]
@samuveth Got this issue when trying the Fleek deployment
image

**Comment by bonustrack** [comment]
For the validation we can do that on another PR

**Review by bonustrack — APPROVED** [review]
Did some test it seem to work well great work!

**Comment by mktcode** [comment]
@samuveth Maybe the directory name could be a bit more suggestive than just the letter S.

**Comment by samuveth** [comment]
> @samuveth Maybe the directory name could be a bit more suggestive than just the letter S.

@bonustrack

**Pull request merged**
