### PR TITLE
chore: improve connect wallet modal

### PR DESCRIPTION
**Pull request by bigint**
**Before**

Screenshot 2021-12-11 at 8 58 49 PM

Screenshot 2021-12-11 at 8 59 38 PM

**After** (reduce icon size, center aligned)

Screenshot 2021-12-11 at 8 58 30 PM

Screenshot 2021-12-11 at 8 59 59 PM

### CODE REVIEW

**Review by samuveth — APPROVED** [review]
Looks good

**Comment by samuveth** [comment]
@bigint can you resolve conflicts

**Comment by bigint** [comment]
@samuveth resolved now 👍🏻

**Pull request merged**
