### PR TITLE
Add admins field in settings

### PR DESCRIPTION
**Pull request by samuveth**
Requires: https://github.com/snapshot-labs/snapshot.js/pull/194

### CODE REVIEW

**Review by ChaituVR — COMMENTED** [review]
Looks good to me 👍 

@bonustrack 
can we add an info icon (with tooltip maybe) somewhere in this field to explain the difference between members and admins?
image

**Comment by ChaituVR** [comment]
is it possible/good to auto-populate the space owner's address also? (non-deletable)

or can we display this field as a deletable list, for example:
image

**Review by bonustrack — APPROVED** [review]
Looks good!

**Comment by samuveth** [comment]
> is it possible/good to auto-populate the space owner's address also? (non-deletable)
> 
> or can we display this field as a deletable list, for example:
> image

I like the idea, I think we should consider this.

**Comment by bonustrack** [comment]
@ChaituVR @samuveth We can do this on another PR, still need to figure out the UX for it. I was thinking to do something more like GitHub, where you see admins and members all together and have a way to select which address is members or admin.

**Pull request merged**
