### PR TITLE
Remove overflow prevent and show black overflow on darkmode

### LINKED ISSUE #1344: mobile: Can't swipe down to reload page
```
body {
  overscroll-behavior-y: none;
}
```
This is preventing swipe down refresh on mobile browsers. I think you added this to prevent over scrolling on macOS @bonustrack ?

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #1344 

Like on github when darkmode is enabled the overflow will be dark too.

### CODE REVIEW

**Comment by samuveth** [comment]
Anyone have an iPhone to test this?

**Comment by mktcode** [comment]
I don't have an iPhone but I can confirm that I can refresh by scrolling down in Chrome on my old android.

**Comment by mktcode** [comment]
I wonder a bit why you are doing it in JS though. What about this:

```css
@media (pointer: fine) {
  body {
    overscroll-behavior-y: none;
  }
}
```

**Review by mktcode — APPROVED** [review]

**Comment by bonustrack** [comment]
Yes, can you make it just CSS?

**Comment by mktcode** [comment]
Done. Works for me on android but give it another try on your fruit devices.... :)

**Comment by samuveth** [comment]
Works for me too. Can't test on fruit either 😆

**Pull request merged**
