### PR TITLE
Replace ipfsGet with graphql query

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
[Use GraphQL API to get single proposal](https://trello.com/c/xJarIwi9/79-use-graphql-api-to-get-single-proposal)

**Comment by bonustrack** [comment]
When i try to vote there it doesn't work i got this error message before the confirm modal:
image

**Comment by bonustrack** [comment]
Otherwise it seem to work well!

**Comment by samuveth** [comment]
@bonustrack this PR has been continued here https://github.com/snapshot-labs/snapshot/pull/364 because of possible merge conflicts.

**Comment by bonustrack** [comment]
Can't we review / merge first this one? (separately from the terms modals)

**Comment by samuveth** [comment]
@bonustrack Okay, lets try that

**Review by bonustrack — APPROVED** [review]
Seem to work well

**Pull request merged**
