### PR TITLE
feat(): added a theme switcher

### LINKED ISSUE #647: Add dark mode switcher
We should add an icon (using icon id "sun" and "moon") on the left sidebar like this:
image
For the dark mode we can use the colors from Loot DAO skin. By default we should show default OS setting of the user see example with Uniswap skin https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/uniswap.scss#L12 . The space having specific skin should keep their colors. Dark / light mode should be used only when there isn't any space skin. The value dark / light should be stored on localStorage.

### PR DESCRIPTION
**Pull request by harshmaur**
Fixes #647 

- implemented a hook to get the current userSkin

### CODE REVIEW

**Comment by bonustrack** [comment]
@harshmaur Dark mode doesnt persist for me, when i refresh the page it comeback to white.

**Comment by harshmaur** [comment]
@bonustrack it will work now.

**Comment by samuveth** [comment]
@harshmaur the button on `/setup` should be blue after entering a valid ENS. Currently it looks like this 
image

**Comment by samuveth** [comment]
@harshmaur the button on `/setup` should be blue after entering a valid ENS. Currently it looks like this 
image

**Comment by samuveth** [comment]
@harshmaur the same for `/delegate` 
image

**Comment by samuveth** [comment]
@harshmaur the `<pre>` `<code>` tags in mardown have white text on white background. See here
https://bafybeicklqgphzqkjozy672ddkeiauydp5kybkih7royq7ujkdjt3xthrm.on.fleek.co/#/strategy/erc20-balance-of

**Comment by bonustrack** [comment]
- Can you make these skins works with the dark mode switcher? https://github.com/snapshot-labs/snapshot-spaces/search?q=prefers-color-scheme
- Change icon color for sun and moon to same color than the others icons Timeline and Help

**Comment by bonustrack** [comment]
- Can change the color of the text inside the active proposal indicator here 
image

**Comment by samuveth** [comment]
@harshmaur can you resolve conflicts, then I'll merge this

**Comment by harshmaur** [comment]
Done!!

**Review by bonustrack — APPROVED** [review]
Well done @harshmaur!

**Pull request merged**
