### PR TITLE
Use EIP712 with Coinbase wallet

### PR DESCRIPTION
**Pull request by bonustrack**

### CODE REVIEW

**Comment by samuveth** [comment]
Doesn't work for me 
image

**Comment by midgerate** [comment]
Yep. This is the same problem I faced with coinbase. @bonustrack

**Comment by bonustrack** [comment]
@midgerate @samuveth Did you tested locally? Do you use the iOS app?

**Comment by samuveth** [comment]
@bonustrack no used android and I the preview build.

**Comment by bonustrack** [comment]
@samuveth Weird, do you have latest version of Coinbase wallet?

**Pull request closed without merging**
