### PR TITLE
feat: Uma module updates

### PR DESCRIPTION
**Pull request by abg4**
This PR makes updates from feedback and changes that weren't included in #3448.

**Changes in this PR:**
- Add modal that provides users with more information on proposal, bond, and liveness period before proposing.
- Add suffix to UMA functions.
- Remove duplicate `ensureRightNetwork` function
- Remove extra border being shown when proposal is in liveness period
- Shows an error if the bond is greater than the user balance and disables the button.
- Links to the oracle UI when proposal is in liveness to make it easier to dispute invalid proposals.

**How to test and review this PR?**
These changes can be easily tested by going through a Snapshot proposal with an `umaAddress` included in the SafeSnap config.

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
utACK

**Review by samuveth — APPROVED** [review]
utACK

**Comment by mktcode** [comment]
Didn't test yet but couldn't find issues in the code.

**Review by mktcode — APPROVED** [review]

**Comment by abg4** [comment]
Thanks everyone for reviewing. @bonustrack anything else that needs to be done before we can merge?

**Comment by bonustrack** [comment]
@abg4 All good! Just merged

**Pull request merged**
