### PR TITLE
Show meaningful error when votes download is failing on the demo website

### LINKED ISSUE #4069: [BUG] - votesReport download not working on demo
### Briefly describe the bug.

When trying to download a votesReport on the demo subdomain, it returns a 404 error

### How can we reproduce the bug?

1. Go to https://demo.snapshot.org/#/radiantcapital.eth/proposal/0x42db9f47567ac9826e5f78139975ab15f6e985ddde93459d1c53b6dd990fd952
2. Click on the button to download the votesReport
3. It shows a modal saying there's trouble connecting to the download server

### What is the expected behaviour?

It should show another message, such as unsupported network

### Can you attach screenshots?

_No response_

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

### PR DESCRIPTION
**Pull request by wa0x6e**
### Issues

Fixes #4069 

Votes report download is not working on the demo website. It will not work, as votes report are available only on the main network on sidekick side.

We should show a meaningful error message, and avoid triggering the download request, on the demo website.

### Changes 

1. Add a filter to not trigger the download request on demo environment
2. Show a `unsupported network` error message when trying to download a votes report on demo env

### How to test

1. Change your local instance env to demo
2. Open the app with yarn dev
3. To to a proposal
4. Click on the votes report download button
5. It should show a message saying that the network is not supported
6. If you open the dev network tab, you should also not see a request to sidekick server

This is not testable on the vercel/fleek preview, as they're not on the correct 'demo' env to show the correct message

### Self-review checklist
- [x] I have performed a full self-review of my changes
- [ ] I have tested my changes on a preview deployment
- [ ] I have tested my changes on different screen sizes (sm, md)
- [ ] I have tested my changes on a custom domain

### Additional notes or considerations
*_(Include any other relevant information or context that may be helpful for the reviewer)_*

### CODE REVIEW

**Comment by samuveth** [comment]
The demo utilizes a HUB known as "testnet.snapshot.org" for its operations. Although the name may suggest it is network-related, it's a bit misleading, as it doesn't actually pertain to network matters. The error message should be renamed and any references to the network should be removed. The current wording could mislead users into thinking they need to change the network settings in their connected wallets, which isn't the case.

To avoid future confusion, we should also consider changing the URL of the demo hub to "demo.snapshot.org"

**Comment by wa0x6e** [comment]
Isn't the demo also on georli?

**Comment by samuveth** [comment]
Yes, but this isn't related to voting or proposal creation. Just for space creation

**Comment by samuveth** [comment]
The production hub is also using "hub.snapshot.org" and not "mainnet.snapshot.org" so a name change to "demohub" would make sense IMO

**Comment by wa0x6e** [comment]
fixed

**Review by samuveth — APPROVED** [review]
tACK

**Pull request merged**
