### PR TITLE
fix: use <a> to create links to spaces in sidebar

### PR DESCRIPTION
**Pull request by wa0x6e**
Prefer `<a>` instead of `<div>` with an onClick event, to not break keyboard navigation

### Issues
Current link to spaces in the sidebar are created using a `<div>` + `onClick` event. These are not considered as native links by the browser, and are skipped when navigating the page using the keyboard.

Fix some part of #3707 

### Changes 
Use `<router-link>` to create link to spaces in the sidebar, instead of `<div>` + onClick event

### How to test
Sidebar links should behave as before. They are just now focusable when using keyboard navigation

1. Open any page
2. Click on `TAB` key, and navigate through the sidebar
3. You should see that spaces link are now focusable
4. Focus any space, and click `ENTER`
5. You should navigate to the space page

### Self-review checklist
- [x] I have performed a full self-review of my changes
- [x] I have tested my changes on a preview deployment
- [ ] I have tested my changes on a custom domain
- [x] I have run end-to-end tests `yarn cypress:test:e2e`, and they have passed

### Additional notes or considerations
I am not aware of why the div/onClick event choice has been made, over the `<router-link>` one. Is there any reason, or edge case explaining this choice ?

### CODE REVIEW

**Review by samuveth — APPROVED** [review]
tACK

**Comment by samuveth** [comment]
> I am not aware of why the div/onClick event choice has been made, over the `<router-link>` one. Is there any reason, or edge case explaining this choice ?

I think there used to be an edgecase with vue draggable package, but I couldn't find any issues when testing the preview deployment.

**Comment by j0hnfl0w** [comment]
yeah i remember some issues with links and vue-draggable, but now it seems gone. Now we can CMD+Click on a space in a Sidebar to open it in a new tab!

**Review by j0hnfl0w — APPROVED** [review]
tACK

**Pull request merged**
