### PR TITLE
remove fortmatic

### PR DESCRIPTION
**Pull request by midgerate**

### CODE REVIEW

**Comment by samuveth** [comment]
@midgerate where is the v4 change at?

**Comment by midgerate** [comment]
@samuveth I just removed walletlink from personalSign, that way it will by default use typed data

**Comment by samuveth** [comment]
@midgerate  Voting on single choice proposals doesn't work for me anymore with Coinbase wallet (WalletLink) 
image

**Comment by midgerate** [comment]
@samuveth strange. Are you sure it was working when you tested it the last time?

**Comment by samuveth** [comment]
@midgerate can you test yourself? https://www.coinbase.com/wallet

**Comment by midgerate** [comment]
@samuveth @bonustrack added walletlink back for personal sign

**Review by samuveth — APPROVED** [review]

**Pull request merged**
