### PR TITLE
Refactor main components using Comp API part 2

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
@ChaituVR can you help me test this and specially the Topnav component with a custom domain

**Comment by ChaituVR** [comment]
You can edit domains.json file in local and add "localhost": "yam.eth" to test custom domain

**Comment by samuveth** [comment]
@ChaituVR thanks that worked! Please approve after testing it yourself

**Review by ChaituVR — APPROVED** [review]
LGTM .. everything seems working

**Review by bonustrack — APPROVED** [review]
Looks good

**Pull request merged**
