### PR TITLE
New space layout flow

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
@bonustrack @ChaituVR how do you like this flow where the sidebar is persistent of each view.

**Comment by bonustrack** [comment]
@samuveth Hum not a fan, i prefer that the "create" page to use the same layout as the proposal page. Also delegate page the button submit looks too large and must be working without the space context like this: https://snapshot.org/#/delegate

**Comment by samuveth** [comment]
> https://snapshot.org/#/delegate

Where is this being used?

**Comment by samuveth** [comment]
> @samuveth Hum not a fan, i prefer that the "create" page to use the same layout as the proposal page. Also delegate page the button submit looks too large and must be working without the space context like this: https://snapshot.org/#/delegate

Both seem fixable. I strongly feel that the sidebar should either persist of not be used for "New proposal" and "Delegation". I'm working on something that might work out.

**Comment by samuveth** [comment]
Will look into this more at a later time.

**Pull request closed without merging**
