### PR TITLE
use dayjs

### LINKED ISSUE #887: Implement date formatting library (day.js)
Currently date formatting is handled manually.

https://github.com/snapshot-labs/snapshot/blob/8445db98a1d77547ac25760a20fb1cd2641af695/src/components/TimelineProposal.vue#L46
https://github.com/snapshot-labs/snapshot/blob/8928d8957a145da2b20f919a0ecfe1e8544d8837/src/helpers/utils.ts#L134-L146

To reduces knowledge-silos and leverage existing code and getting some convenience for free, this can be replaced by a date library like [day.js](https://day.js.org/), since date formatting will be a reoccurring thing anyways.

After some evaluation, day.js seems to be a reasonable choice, even though the long term vision is to eradicate the need for libraries entirely as the browser-native APIs evolve, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format.

(This issue emerged from: https://github.com/snapshot-labs/snapshot/issues/709)

### PR DESCRIPTION
**Pull request by KennethAshley**
# Why?
Reduces knowledge silos and leverages existing code and gets some convenience for free. 

Fixes #887.

Changes proposed in this pull request:
- remove timeago.js
- add dayjs
- use dayjs methods for `ms`, `calcFromSeconds`, and `calcToSeconds `
- updates input values to be `hours` and `days` for dayjs unit

### CODE REVIEW

**Comment by bonustrack** [comment]
@KennethAshley Its looks good but I'm not able to see date in another language than English, is this supposed to be like this? Isn't day.js having such translation for "in 1 day"?

**Comment by bonustrack** [comment]
@snapshot-labs/frontend Who want take over this PR? Need to resolve conflicts and test it properly.

**Comment by mktcode** [comment]
After finishing some other open stuff... If nobody else picks it up during the week, I can.

**Comment by bonustrack** [comment]
@mktcode Will pick this

**Comment by mktcode** [comment]
Closed in favor of: https://github.com/snapshot-labs/snapshot/pull/1257

**Pull request closed without merging**
