### PR TITLE
feat: Highlight user vote

### LINKED ISSUE #1167: Highlight users vote
The users vote should be highlighted in the votes block

Example
image

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1167

Screenshot 2021-12-10 at 9 55 11 AM

### CODE REVIEW

**Comment by samuveth** [comment]
I've tried this one before but it doesn't look good on lightmode.

**Comment by bonustrack** [comment]
Not too fan of changing the style here, this row is not clickable and we don't use such highlight anywhere on the app, there is ton of skins for custom domains where this may not render well.

**Comment by bigint** [comment]
Makes sense @samuveth feel free to close this 🙏🏻

**Comment by bonustrack** [comment]
Closing this PR for now

**Pull request closed without merging**
