### PR TITLE
fix: Improve linting speed

### PR DESCRIPTION
**Pull request by samuveth**
https://github.com/vuejs/eslint-config-prettier#use-separate-commands-for-linting-and-formatting

### CODE REVIEW

**Comment by wa0x6e** [comment]
Would that have any effects on tue current lint task ? Would that require to run prettier for formatting ?

**Comment by samuveth** [comment]
Yes, but they recommend formatting should be handled in the IDE. Lint should only handle code quality checks.

**Comment by samuveth** [comment]
I've added the extensions.json so that it is more clear that prettier is required.

**Comment by samuveth** [comment]
I just realized that we had `prettier --write` on pre-commit in package.json. I removed `eslint --fix` since we already have a workflow for that, and it was slowing down each commit by a lot. What do you think @wa0x6e?

**Comment by wa0x6e** [comment]
Running `prettier --fix` and `eslint --fix` separately will be faster than just `eslint --fix` with prettier config ?

**Comment by samuveth** [comment]
We are not running both anymore together.

**Review by wa0x6e — APPROVED** [review]
utAck

**Review by cryptoinvest87768 — COMMENTED** [review]
[SlowMist Audit Report - Rabby Wallet-2023.07.20.pdf](https://github.com/snapshot-labs/snapshot/files/13357872/SlowMist.Audit.Report.-.Rabby.Wallet-2023.07.20.pdf)

**Pull request merged**
