### PR TITLE
update src/locales/zh-CN.json ,Chinese language about vote

### PR DESCRIPTION
**Pull request by jambestwick**
Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by bonustrack** [comment]
@jambestwick Hi sir, translation must be done in our Crowdin page here: https://translate.snapshot.org It doesn't work if we publish from an external PR.

**Comment by jambestwick** [comment]
ok

**Comment by samuveth** [comment]
https://crowdin.com/project/snapshot-labs

**Review by jambestwick — COMMENTED** [review]
commit

**Pull request closed without merging**
