### PR TITLE
Use <script setup> on pages

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by bonustrack** [comment]
Fleek build fail with this error:
image
I got the same error in local when i do use `serve` script

**Comment by bonustrack** [comment]
I would recommend update others dependencies to latest version, it may help Vue has a next version 3.1.4 (now we are using 3.1.2)

**Comment by samuveth** [comment]
@bonustrack how does it work for you now?

**Review by bonustrack — APPROVED** [review]
Works well for me now

**Comment by samuveth** [comment]
Awesome

**Pull request merged**
