### PR TITLE
feat: add social section

### LINKED ISSUE #1595: Space About page should display social links if configured in the settings.
UI 
image

@bonustrack to approve the design

Social Links to allow
Twitter - Take user name
Github - Take username / organization 
Discord- Take discord id (the one after discord.gg/)

### PR DESCRIPTION
**Pull request by bigint**
Fixes #1595

Screenshot 2022-02-02 at 8 23 45 PM

### CODE REVIEW

**Comment by bigint** [comment]
cc @samuveth @bonustrack @mktcode 

Is there discord in social? feel free to comment design changes I'll update accordingly 🤗

**Comment by mktcode** [comment]
The spacing is a bit off and for my taste it's a bit too prominent like this. I'd either make them slightly transparent and then opaque on hover or maybe this isn't even the right place for them. Was just a very quick suggestion from my side. Sometimes it needs a day or two to find consent on these little things. Better to wait a bit then before taking action. Your commitment is absolutely appreciated though! Don't get me wrong! 👍🏻

**Comment by midgerate** [comment]
@bigint yeah we need discord too, have to add that additionally to the settings.

**Comment by samuveth** [comment]
I think we can close this on for now and continue discussion in the linked issue.

**Comment by mktcode** [comment]
I thought the new PR is branched out from this one but it's not. Commits are lost now. Well... so be it. Not a big deal here. But I think the more we want to be an open, community driven project in the future, the more this becomes a no-go.

**Comment by midgerate** [comment]
@mktcode yeah, I could not figure that out, but I gave credits in the commit message that I made. https://github.com/snapshot-labs/snapshot/pull/1881

**Comment by mktcode** [comment]
On a PR from a fork you can do this:
image
And then push it as a new branch.

**Pull request closed without merging**
