### PR TITLE
Refactor getSpaces and only load all spaces when needed

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by samuveth** [comment]
Still has many bugs, just pushed it so keep it safe

**Comment by samuveth** [comment]
[Remove getSpaces from init](https://trello.com/c/7LI1pRxj/271-remove-getspaces-from-init)

**Comment by samuveth** [comment]
@bonustrack I feel like this is much better now. We now use an array for the spaces object across the whole UI and we only load single spaces from the graphql api if we don't have all spaces loaded already, so basically that only happens when someone loads a space or a proposal directly from the URL. That also fixes the loading UI when switching between spaces.

**Comment by bonustrack** [comment]
Can put this one in standby first, we will look on others way to load this data.

**Comment by samuveth** [comment]
[Remove getSpaces from init](https://trello.com/c/7LI1pRxj/271-remove-getspaces-from-init)

**Comment by samuveth** [comment]
No longer needed

**Pull request closed without merging**
