### PR TITLE
feat: Add modal to show spaces in mobile

### PR DESCRIPTION
**Pull request by bigint**
https://user-images.githubusercontent.com/69431456/145699739-d9d96900-3d42-4ad4-b61f-2c602f4eb387.mov

### CODE REVIEW

**Comment by bigint** [comment]
Please suggest some icon to add instead of plus, I just added it for testing

**Comment by samuveth** [comment]
I think it would be better to wait for UX/Design team on this one.

**Comment by mktcode** [comment]
We'll close this one, as the responsiveness is not a priority. We just fix urgent issues but otherwise focus on the actual [app](https://github.com/snapshot-labs/snapshot-app).

**Pull request closed without merging**
