### PR TITLE
chore: Update vue to v3.2.26 and vite to v2.7.2

### LINKED ISSUE #1082: Update Vue and Vite to latest beta version
Vue is on 3.2.24 https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md
Vite has 2.7.0 https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md
We should test that voting is working fine on the different connectors (Metamask, WalletConnect, Coinbase...etc)

### PR DESCRIPTION
**Pull request by bigint**
Update vue to v3.2.26 and vite to v2.7.2

Fixes #1082

### CODE REVIEW

**Review by samuveth — APPROVED** [review]
Looks good!
Tested voting and proposal creation with main connectors.

**Comment by bonustrack** [comment]
Did you tested locally @samuveth ?

**Comment by samuveth** [comment]
> Did you tested locally @samuveth ?

Yes

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
