### PR TITLE
Layout fixes 2

### LINKED ISSUE #1989: Layout improvement 2
1: This should look same before, on the same line
image

2: We should increase space here by half of current size 
image

3: We should show the network here and use it for the exploreUrl (not it take the network for the space and fail)
image

4: This font size should be smaller, similar than the block title font size
image

5: Proposal state and avatar are too close together we should add more space
image

6: We should not have white border when focus on a button
image

7: On proposal page when scrolling to the end of the page the space should be bigger
image

8: The footer should start and end in same level than the main content
9: The button should take full width
10: The space should be smaller
image

11: We shouldnt see 0 spaces if it's still loading
image

### PR DESCRIPTION
**Pull request by mktcode**
Fixes #1989.

3. has its own issue: https://github.com/snapshot-labs/snapshot/issues/1980

### CODE REVIEW

**Comment by bonustrack** [comment]
Load more button should also be full width on mobile, and we should have border between space on mobile, between strategies, networks, plugins too
Screenshot_20220324-160858_Chrome

Also here, the blocks should have top border, now it feel like block title belong to previous block 
Screenshot_20220324-161042_Chrome

**Comment by mktcode** [comment]
done.

**Comment by bonustrack** [comment]
@mktcode Border color on dark theme is wrong
image

**Comment by mktcode** [comment]
Aaaargh! Daaamn you, darkmode!

fixed :)

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
