### PR TITLE
add space name to proposal information section

### PR DESCRIPTION
**Pull request by rootial**
## Summary
Fixes  https://github.com/snapshot-labs/snapshot/issues/1226

## Test
Kapture 2021-12-11 at 22 35 12

## Reviewer
@bonustrack @samuveth @ChaituVR

### CODE REVIEW

**Comment by bigint** [comment]
Looks good, and also i agree adding it there because we don't display space name anywhere on that page 😃

**Comment by samuveth** [comment]
@rootial can you resolve the conflicts

**Comment by rootial** [comment]
@samuveth conficts resolved.

**Comment by samuveth** [comment]
@bonustrack waiting for your approval on this one.

**Comment by rootial** [comment]
This PR needs another Review, is it caused by my branch name `develop`? @samuveth

**Comment by rootial** [comment]
Hi @samuveth i have closed this pr and submit another pr using my branch name https://github.com/snapshot-labs/snapshot/pull/1266
please take a look thx

**Comment by mktcode** [comment]
> This PR needs another Review, is it caused by my branch name develop? @samuveth

@rootial No, your branch names are yours. We have set up the repositories so that they require reviews before merging is possible.

**Pull request closed without merging**
