### PR TITLE
Remove redundant CSS and !important

### PR DESCRIPTION
**Pull request by samuveth**
Fixes https://github.com/snapshot-labs/snapshot/issues/1452

Changes proposed in this pull request:
- Remove redundant CSS classes from style sheet
- Remove !important when possible

### CODE REVIEW

**Comment by samuveth** [comment]
Screen Shot 2022-02-19 at 10 09 16 PM
🎉

**Comment by samuveth** [comment]
These is a lot more that can be done, but I think this is enough for one PR

**Comment by mktcode** [comment]
(irony off) Will be fun to review! Perfect for a stormy sunday afternoon tomorrow. :D

**Comment by midgerate** [comment]
Crazy PR!

**Comment by samuveth** [comment]
> Crazy PR!

Messaged you on discord.

**Review by bonustrack — APPROVED** [review]
Nice!

**Comment by mktcode** [comment]
Eeeeeeey... I wanted to review this! 🤪 Joking aside... nice job.

**Pull request merged**
