### PR TITLE
Fix quadratic voting on  small screens

### PR DESCRIPTION
**Pull request by samuveth**
Based on https://github.com/snapshot-labs/snapshot/pull/425

### CODE REVIEW

**Comment by bonustrack** [comment]
- Can you remove the + and - on small screen, using a breakpoint ~420 (input should have border left and right)
- If under the breakpoint use 18 chars for the choice label.

**Comment by samuveth** [comment]
@bonustrack using CSS to shorten the choice string seems like the better solution.

You can also test it here: https://bafybeig4xx5xn3dp4nsspuefoaqzlfacqhj3qcpebecsg2s27dbuzhsqry.on.fleek.co/#/samuv.eth/proposal/QmU23RfL5F2iwfPjHXFoqhDKdQqf1fwT4KQUV2DFGD4yrP

I don't think incrementing the choice by clicking on it would be good because it would also trigger the tooltip.

**Comment by samuveth** [comment]
@bonustrack can we get this merged?

**Review by bonustrack — APPROVED** [review]

**Comment by bonustrack** [comment]
Yes you can merge it

**Pull request merged**
