### PR TITLE
Add WalletLink and fix errors with patch-packet

### LINKED ISSUE #528: Add Coinbase wallet connect
This is how it was done before, but it was disabled due to an issue:
- https://github.com/snapshot-labs/snapshot/blob/c451f46a450ca779520e4cbd6977960ae6c3cad7/src/helpers/connectors.json#L31-L40
- https://github.com/snapshot-labs/snapshot/blob/c451f46a450ca779520e4cbd6977960ae6c3cad7/src/helpers/auth.ts#L4

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #528

### CODE REVIEW

**Comment by samuveth** [comment]
image
This error still needs to be fixed

**Comment by bonustrack** [comment]
@ChaituVR Please report here what's issue you got so others can help

**Comment by ChaituVR** [comment]
Works fine with `yarn dev` but when I build with `yarn build` i see this following error in browser
image

**Comment by bonustrack** [comment]
@ChaituVR What the reason of having "walletlink" in` devDependencies` instead of `dependencies`? Also can you fix conflicts?

**Comment by ChaituVR** [comment]
@bonustrack Fixed conflicts

**Review by bonustrack — APPROVED** [review]
Looks good, just need to fix the new conflicts

**Pull request merged**
