### PR TITLE
fix: center align checkbox and remove left padding in settings

### PR DESCRIPTION
**Pull request by bigint**
After

Screenshot 2022-01-30 at 8 02 27 PM

Before

Screenshot 2022-01-30 at 8 02 57 PM

### CODE REVIEW

**Comment by bigint** [comment]
cc @samuveth

**Comment by mktcode** [comment]
There's a checkbox on the delegate page too. https://bafybeihc76h6jxwmga454smopsw4ehllrszxxpp2qai2s7vmr5vf4x464u.on.fleek.co/#/delegate

But I think there's a better fix for this. Try giving the `<a>` in `Checkbox.vue` a `class="flex"`. This solves the actual issue of the checkbox not filling the available space.

**Comment by samuveth** [comment]
Thanks @bigint
Yes I agree we should solve this with flexbox

**Review by samuveth — CHANGES_REQUESTED** [review]
Use flexbox instead of mt-1

**Review by samuveth — APPROVED** [review]
Hm just saw they already use flexbox, couldn't find a way to fix this any other way so I'll approve this.

**Pull request merged**
