### PR TITLE
[safeSnap] refactored to use script setup syntax

### PR DESCRIPTION
**Pull request by mktcode**
Fixes https://github.com/snapshot-labs/snapshot/issues/1549

The issue was that `this.$i18n` wasn't available, leading to "is undefined" errors.. There was probably a simpler fix but mixing options and composition API has its quirks anyway, so I refactored the component entirely, to use `<script setup>`.

@carlosfebres your opportunity to make youreself familiar with the composition API if you haven't already. ;)

### CODE REVIEW

**Comment by carlosfebres** [comment]
> @carlosfebres your opportunity to make yourself familiar with the composition API if you haven't already. ;) 

for sure! I'll try to refactor every component I work on from now on 👍🏻

**Review by samuveth — APPROVED** [review]
Tested and works well

**Comment by mktcode** [comment]
> I'll try to refactor every component I work on from now on 👍🏻

Don't feel pressured though. Only if time allows for it! 🤪  But yea, it's just way better compared to the old style. By having just a giant object with properties like (`methods` and `computed`, `created`, etc) things can become super in-transparent very quickly.... if you then add mixins... good night. :D New style is much more dev (and IDE) friendly.

**Comment by samuveth** [comment]
@carlosfebres also the Volar extension has better support than Vetur for the new API.

**Pull request merged**
