### PR TITLE
truncate long user names

### PR DESCRIPTION
**Pull request by mktcode**
Fixes:

image

### CODE REVIEW

**Comment by bonustrack** [comment]
@mktcode Where is this proposal to test? I'd prefer using `_shorten` function, this is how we do everywhere else

**Comment by mktcode** [comment]
Hm... I thought that's only used for addresses, where you want to keep the last part and put dots in the middle. CSS has the advantage that it automatically adjusts to the element's size, which gives you some responsiveness for free. Currently it overlaps on small screens even with js-shortened names.

image

**Review by bonustrack — APPROVED** [review]
LGTM

**Comment by midgerate** [comment]
@mktcode so something like this is better? 
image

See the address with core.

**Comment by bonustrack** [comment]
The double "..." doesnt looks good

**Review by ChaituVR — APPROVED** [review]

**Comment by mktcode** [comment]
Indeed that doesn't look nice. Seems there isn't a perfect solution for this other than just making sure there's enough space.

And extra address component could do this:
ezgif-2-bfc573379307
But I'm not sure if that's worth the effort.

**Pull request merged**
