### PR TITLE
TimelineProposalPreview shows time since starting date instead of rem…

### PR DESCRIPTION
**Pull request by stormsson**
The TimelineProposalPreview component shows all active proposals, with a text "XYZ time left".
the time is calculated from the proposal.start time instead of proposal.end, giving the wrong amount of remaining time.

In the following example the displayed time should be something similar to "14 days left" 

image

image

### CODE REVIEW

**Comment by Qsnh** [comment]
I think there is no problem here. The display here should be how much time has passed since the creation time, not how much time is left before the end time.

**Comment by samuveth** [comment]
@stormsson is correct I think, it should show how much time is left.

**Review by samuveth — APPROVED** [review]
Looks good! @bonustrack do you approve this?

**Review by bonustrack — APPROVED** [review]
Good catch! Thanks @stormsson

**Pull request merged**
