### PR TITLE
look up domain name by hash for non-.eth domains

### PR DESCRIPTION
**Pull request by mktcode**
Fixes:

image

For non-.eth domains, the ENS subgraph only returns a hash. Props to @ChaituVR for figuring out how to retrieve the actual name from that hash. I have to admit that I still don't fully understand why and what and so on but the lookup works, at least for this exact case.

I'm not sure if setting the text record will work with these domains then.

https://github.com/snapshot-labs/snapshot/blob/46fe1b9b8b8dac8944e566f1c0d33838af28f8bb/src/composables/useSpaceController.ts#L63-L69

Didn't find a way to test this.

### CODE REVIEW

**Comment by samuveth** [comment]
I'm trying to register a .xyz domain on ENS, might take until tomorrow until that's done and I can test this

**Comment by mktcode** [comment]
Reminder: Need to test subdomains too.

**Review by samuveth — APPROVED** [review]
Works well for me

**Comment by mktcode** [comment]
User confirmed successful space creation as well.

**Pull request merged**
