### PR TITLE
fix: Change back button and add combobox

### LINKED ISSUE #1430: Add strategy documentation link in settings page
There should be a way to suggest to users that there is documentation available for each strategy within the settings page (when selecting a particular strategy)

Maybe we can add an info icon to the strategy modal, and on click should go to particular strategy ex: https://snapshot.org/#/strategy/erc20-balance-of
image

Icon:
image

Original discussion:
https://discord.com/channels/707079246388133940/747049240022482974/929975956079259738

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #1430

## Changes

- Change `Back` to `Strategy details` to improve UX when coming directly to the playground from another link
- Add a combobox (with search) enabling the user to switch between strategies directly from the playground

image

https://www.loom.com/share/a11814a3e12f4588a1eebfd85e6df21c

### CODE REVIEW

**Comment by zzuziak** [comment]
Great idea with dynamic strategy change. @samuveth could you possible do a short loom recording with how it works and to also show the loading times? :pray:

**Comment by samuveth** [comment]
@zzuziak sure 
https://www.loom.com/share/a11814a3e12f4588a1eebfd85e6df21c

**Comment by samuveth** [comment]
@zzuziak any idea why when I past a loom link it doesn't show the video and it shows just a link to it?

**Comment by ChaituVR** [comment]
@samuveth Excellent idea! but not working on a custom domain, clicking on "strategy details" is throwing an error and doesn't take us anywhere, maybe we can hide this link on custom domain, will create a new issue

**Comment by samuveth** [comment]
@ChaituVR good catch. But that didn't work before either ;)

**Pull request merged**
