### PR TITLE
Settings improvements

### PR DESCRIPTION
**Pull request by samuveth**
Fixes https://github.com/snapshot-labs/snapshot/issues/3581

## Changes
- Show warning when leaving settings page with unsaved changes image

- Refactor form pruning to no longer interfere with `hasFormChanged` check
- Move validation form population into populateForm to no longer interfere with `hasFormChanged` check
- Fix space reload loading indicators after saving settings

### CODE REVIEW

**Comment by zzuziak** [comment]
@samuveth would it be a lot of work for you to display a custom modal instead of an alert window from the browser for the unsaved settings?

**Comment by zzuziak** [comment]
I guess they are, but from my perspective as a user (and dev 😁 ) I don't trust the default alert windows. 

Maybe we can have another PR handling all the alert windows to refactor them into our own modal, wdyt?

**Comment by samuveth** [comment]
Yeah probably better to have our own modal. Will add it to this PR because it's pretty simple @zzuziak

**Comment by samuveth** [comment]
@zzuziak 
image

**Pull request merged**
