### PR TITLE
Added page transition

### PR DESCRIPTION
**Pull request by mktcode**
Uses the existing fade transition for `<router-view>`.

page-transitions

Had to move `<teleport>` component into `<Layout>` in some views (to have single root) but shouldn't make any difference.

### CODE REVIEW

**Comment by midgerate** [comment]
LGTM

**Review by midgerate — APPROVED** [review]

**Comment by bonustrack** [comment]
Not a fan of page transition, do you know web2 using such thing? Feel like it add extra time to navigate, I prefer instant navigation

**Comment by mktcode** [comment]
> Not a fan of page transition, do you know web2 using such thing? Feel like it add extra time to navigate, I prefer instant navigation

My personal experience is that most people like it more that way. I'll give you that the transition was a bit too slow though. :P So I adjusted it. Feels better now?

Also:

> At the top level of an app, destinations are often grouped into major tasks (and the tasks may not relate to one another). These screens transition in place using a fade through transition pattern.
<sub>https://material.io/design/navigation/navigation-transitions.html#peer-transitions</sub>

page-transition-google

**Comment by bonustrack** [comment]
Still not a fan 🤷

**Comment by mktcode** [comment]
Then this case is... closed. :D

**Pull request closed without merging**
