### PR TITLE
Use Stamp for space avatars

### PR DESCRIPTION
**Pull request by bonustrack**

### CODE REVIEW

**Comment by samuveth** [comment]
Some space avatars load for longer than 10sec and get stuck on loading

**Comment by bonustrack** [comment]
Works for me
image

**Comment by bonustrack** [comment]
This should be very rare, most likely happen on first global load if you load to many images at once. Can you reproduce? I think what we miss in this PR is just a way to clear cache if space avatar changed

**Comment by samuveth** [comment]
Happening on multiple space in the sidebar, even after reloading the page 
image

**Comment by samuveth** [comment]
Now I see this, but it should show an image
image

**Comment by bonustrack** [comment]
If it doesnt show an image on shot.eth space it's just because the IPFS file isn't loading. It's not an issue of Stamp or this PR.

**Pull request merged**
