### PR TITLE
fix: Rename develop to master branch

### PR DESCRIPTION
**Pull request by ChaituVR**
Recently we renamed our default branch from develop to master, so better if we change the code references

### CODE REVIEW

**Comment by Todmy** [comment]
please consider those lines:
- [BasePluginItem.vue](https://github.com/snapshot-labs/snapshot/blob/a121e09eeb3bbd6527529caa740c0e701ce5d0bd/src/components/BasePluginItem.vue#L39)

**Comment by ChaituVR** [comment]
> please consider those lines: [BasePluginItem.vue](https://github.com/snapshot-labs/snapshot/blob/master/src/components/BasePluginItem.vue#L39C43-L39C43)

Oh oops done ✅ Thank you :)

**Comment by wa0x6e** [comment]
Please consider these lines:
- https://github.com/snapshot-labs/snapshot/blob/35955358e54660c7ac3038d264f8c45ef95387c4/src/components/TheHeader.vue#L10
- https://github.com/snapshot-labs/snapshot/blob/35955358e54660c7ac3038d264f8c45ef95387c4/src/composables/useApp.ts#L10

**Comment by samuveth** [comment]
> Please consider these lines:
> 
> * https://github.com/snapshot-labs/snapshot/blob/35955358e54660c7ac3038d264f8c45ef95387c4/src/components/TheHeader.vue#L10
> * https://github.com/snapshot-labs/snapshot/blob/35955358e54660c7ac3038d264f8c45ef95387c4/src/composables/useApp.ts#L10

This is not needed as `VITE_ENV` or `env` are not related to the branch name.

**Review by samuveth — APPROVED** [review]
utACK

**Comment by samuveth** [comment]
Thanks @ChaituVR I didn't think of this at all.

**Review by wa0x6e — APPROVED** [review]
utAck

**Pull request merged**
