### PR TITLE
chore: use network from strategy first

### LINKED ISSUE #1980: Strategies in proposal should display network information
If a strategy has a network,
- Strategies in the proposal should display network info 
  Go to https://snapshot.org/#/lyra.eth/proposal/0x7240756548266a71c0c59fb86801c791ae9ff151e2c2a3da195fd562ab7e9174
  the strategies modal should contain network information 
image

- On click of playground link, the playground should select strategy's network instead of space's network

### PR DESCRIPTION
**Pull request by rootial**
Fixes #1980 .

Changes proposed in this pull request:
- use network from strategy and default to proposal network
- pass strategy network into playgroup link 
@bonustrack @samuveth @ChaituVR

### CODE REVIEW

**Comment by ChaituVR** [comment]
I think it is good to call block finder here to get the strategy network's block number (before redirection) so it will be easy to check voting power on the playground

@bonustrack Any thoughts?

**Comment by bonustrack** [comment]
I'd rather make such call on playground page instead of adding a loading on the strategies modal. But that's better to do this on another PR.

**Comment by ChaituVR** [comment]
Bump. +1 can we merge this? It is hard to guess the network from strategies

**Comment by samuveth** [comment]
Solved in another PR

**Pull request closed without merging**
