### PR TITLE
[safesnap] Use public node to add network to metamask

### PR DESCRIPTION
**Pull request by ChaituVR**
Related to https://github.com/snapshot-labs/snapshot.js/pull/657

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]

**Review by bonustrack — CHANGES_REQUESTED** [review]
Can you use getProvider instead?

**Comment by ChaituVR** [comment]
It is actually used to add a new network to metamask, we don't actually need brovider/provider here, so replaced with public nodes

**Comment by bonustrack** [comment]
Humm, who don't have mainnet on Metamask?

**Comment by ChaituVR** [comment]
@bonustrack @mktcode Any thoughts on how to handle this?

**Comment by ChaituVR** [comment]
Maybe we can use RPCs from here?

https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.json

**Comment by mktcode** [comment]
I will work on Safesnap a lot in the coming days. Gonna think about it but right now my feeling says it's easiest to simply point to [chainlist.org](https://chainlist.org). The current solution only works for MetaMask anyway.

**Comment by samuveth** [comment]
@ChaituVR any update on this?

**Comment by ChaituVR** [comment]
Closing for https://github.com/snapshot-labs/snapshot/issues/3059

**Pull request closed without merging**
