### PR TITLE
collapse sidebar on small screens

### PR DESCRIPTION
**Pull request by mktcode**
This is not the nicest sidebar mechanic I've ever seen but it does the trick for now.

See [deployment](https://bafybeiaeeivrivyhrnvcfqeuacrnsmjmepbvlijqbb45mx5blnecyg43zq.on.fleek.co/)...

### CODE REVIEW

**Comment by mktcode** [comment]
I kind of anticipated that. :D updated...

**Comment by mktcode** [comment]
Like that? Not too sure about the icons for toggling the sidebar though. Any better suggestions? Caret left/right?

**Review by bonustrack — APPROVED** [review]
Yea like this, looks good!

**Comment by samuveth** [comment]
Hmm, a bit shocked this got merged like this tbh :D

**Pull request merged**
