### PR TITLE
Fix ens names on vote page (#1036)

### LINKED ISSUE #1036: ENS domains aren't showing up for users on first page of votes
When I load a proposal, in the "Votes" sections I can't see the ENS domains for the first 10 voters displayed, I only see it once I click "See more", for some reason

bug

Used this proposal: https://snapshot.org/#/superraredao.eth/proposal/0xc9fa170547b53f870e12127440603b6f67bab905653b99735d869cd3fcfbb40f

### PR DESCRIPTION
**Pull request by gbonumore**
Fixes #1036  .

Changes proposed in this pull request:
- Addresses weren't updated until show more was clicked, now addresses will refresh after votes update.

### CODE REVIEW

**Comment by bonustrack** [comment]
@gbonumore So it seem to work but i can see there is extra request being sent, feel like we are sending request to load profile twice. Can you try debug this?

**Comment by gbonumore** [comment]
@bonustrack I will look into that

**Comment by bonustrack** [comment]
@gbonumore Any update?

**Comment by midgerate** [comment]
https://github.com/snapshot-labs/snapshot/pull/1100 Done here.

**Pull request closed without merging**
