### PR TITLE
Add voting type link to docs

### PR DESCRIPTION
**Pull request by samuveth**

### CODE REVIEW

**Comment by ChaituVR** [comment]
Looks good .. can we add an external link icon? or not relevant here?
image

**Comment by samuveth** [comment]
@ChaituVR how is that now?

**Comment by ChaituVR** [comment]
Looks good to me 

But can we remove `voting` from name, because anyway we have `Voting system:`, so that it would be like `Voting system: single choice`... Not sure if we can remove that word or not.. Just a thought.. Shortening looks good too :)

**Comment by bonustrack** [comment]
Can you move strategies in the block information after IPFS?

**Comment by bonustrack** [comment]
Maybe instead of opening the docs we can show the description of the voting system in a modal. What you think @samuveth ?

**Comment by samuveth** [comment]
> Maybe instead of opening the docs we can show the description of the voting system in a modal. What you think @samuveth ?

Yes, I'll give it a try.

**Comment by samuveth** [comment]
Most voting types have a one or two line discription, It would look weird to have a modal just for that I think.

**Comment by bonustrack** [comment]
Closing this for now until we find a better solution, most likely changing thing on the block to cast a vote.

**Pull request closed without merging**
